In [20]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\dv2041tu\anaconda3\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\dv2041tu\anaconda3\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\dv2041tu\anaconda3\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\dv2041tu\anaconda3\lib\site-packages (from nltk) (2024.9.11)
Requirement already satisfied: tqdm in c:\users\dv2041tu\anaconda3\lib\site-packages (from nltk) (4.66.5)
Requirement already satisfied: colorama in c:\users\dv2041tu\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [21]:
!pip install textblob

Requirement already satisfied: textblob in c:\users\dv2041tu\anaconda3\lib\site-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in c:\users\dv2041tu\anaconda3\lib\site-packages (from textblob) (3.9.1)
Requirement already satisfied: click in c:\users\dv2041tu\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (8.1.7)
Requirement already satisfied: joblib in c:\users\dv2041tu\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\dv2041tu\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (2024.9.11)
Requirement already satisfied: tqdm in c:\users\dv2041tu\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (4.66.5)
Requirement already satisfied: colorama in c:\users\dv2041tu\anaconda3\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)

In [22]:
#Importing NLP libraries
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger_eng')
from nltk import ne_chunk
nltk.download('maxent_ne_chunker_tab')
nltk.download('words')
import textblob, string, re  #For text processing and regex operations
from nltk.corpus import stopwords  #For removing common words
from textblob import TextBlob, Word  #For sentiment analysis and word processing
from nltk.stem import PorterStemmer, WordNetLemmatizer  #For word normalization
from bs4 import BeautifulSoup  #For parsing HTML content

#Importing data visualization and manipulation libraries
import matplotlib.pyplot as plt  # For creating plots and visualizations
import pandas as pd  # For data manipulation and analysis
import numpy as np  # For numerical operations

#Suppress warning messages for clean output 
from warnings import filterwarnings
filterwarnings('ignore' )

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DV2041TU\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\DV2041TU\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\DV2041TU\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     C:\Users\DV2041TU\AppData\Roaming\nltk_data...
[nltk_data]   Package maxent_ne_chunker_tab is already up-to-date!
[nltk_data] Downloading package words to
[nltk_data]     C:\Users\DV2041TU\AppData\Roaming\nltk_data...
[nltk_data]   Package words is already up-to-date!

In [23]:
#Configure pandas display options for better data visibility
pd.set_option('display.max_rows', 1000)      #Shows up to 1000 rows
pd.set_option('display.max_columns', 1000)   #Shows up to 1000 columns
pd.set_option('display.width', 1000)         #Sets maximum width of the display
pd.set_option('display.max_colwidth', None)  #Shows full content of each cell (no truncation)

In [24]:
text= """
I can't wait for the Season 5 of Stranger Things🤩❤!
The global AI market is valued at over $390 billion and is projected to increase in value by over 5x in the next 5 years😲. 
'Friends, Romans, countrymen, lend me your ears: I come to bury Caesar, not to praise him.'
<html><body>Welcome to Text Pre-processing!</body></html>
"🐍Python" is a great programming language!!! ??
"""

In [25]:
print(text)

I can't wait for the Season 5 of Stranger Things🤩❤!
The global AI market is valued at over $390 billion and is projected to increase in value by over 5x in the next 5 years😲.
'Friends, Romans, countrymen, lend me your ears: I come to bury Caesar, not to praise him.'
<html><body>Welcome to Text Pre-processing!</body></html>
"🐍Python" is a great programming language!!! ??

In [26]:
#Splits the text based on newline
sentences_text = text.split("\n")
#Converts the list of sentences to a pandas Series
text_to_series = pd.Series(sentences_text)
#Extracts all sentences except the first and last (which might be empty or headers)
text_vector = text_to_series[1:len(text_to_series)-1]
#Create DataFrame with the sentences, using "sentences" as the column name
tdf = pd.DataFrame(text_vector, columns = ["sentences"])

In [27]:
#Converts all text to lowercase
tdf["lower_case"] = tdf["sentences"].apply(lambda x: " ".join(x.lower() for x in x.split()))
#Removes all punctuation marks from the text
tdf["punctuations_removed"] = tdf["lower_case"].apply(lambda x: "".join([letter for letter in x if letter not in string.punctuation]))
#Removes all numeric digits from the text using regex
tdf["numbers_removed"] = tdf["punctuations_removed"].str.replace("\\d", "", regex=True)

In [28]:
!pip install emoji
import emoji
#Removes all emojis from the text
tdf["emojis_removed"] = tdf["numbers_removed"].apply(lambda text: "".join(c for c in text if c not in emoji.EMOJI_DATA))

Requirement already satisfied: emoji in c:\users\dv2041tu\anaconda3\lib\site-packages (2.14.1)

In [29]:
# Get a list of English stopwords (common words like 'the', 'a', 'an', etc.)
sw = stopwords.words("english")
tdf["stopwords_removed"] = tdf["emojis_removed"].apply(lambda x: " ".join(word for word in x.split() if word not in sw))

In [30]:
#Tokenization - breaks down a piece of text into smaller units called tokens
tdf["tokenized"] = tdf["stopwords_removed"].apply(lambda x: TextBlob(x).words)
#Stemming - words are stemmed or diminished to their root form
tdf["stemmed"] = tdf["stopwords_removed"].apply(lambda x: " ".join([PorterStemmer().stem(word) for word in x.split()]))
tdf

                                                                                                                     sentences                                                                                                                  lower_case                                                                                                      punctuations_removed                                                                                                      numbers_removed                                                                                                      emojis_removed                                                      stopwords_removed                                                                          tokenized                                                         stemmed
1                                                                          I can't wait for the Season 5 of Stranger Things🤩❤!                                                                         i can't wait for the season 5 of stranger things🤩❤!                                                                         i cant wait for the season 5 of stranger things🤩❤                                                                     i cant wait for the season  of stranger things🤩❤                                                                      i cant wait for the season  of stranger things                                       cant wait season stranger things                                             [cant, wait, season, stranger, things]                                 cant wait season stranger thing
2  The global AI market is valued at over $390 billion and is projected to increase in value by over 5x in the next 5 years😲.   the global ai market is valued at over $390 billion and is projected to increase in value by over 5x in the next 5 years😲.  the global ai market is valued at over 390 billion and is projected to increase in value by over 5x in the next 5 years😲  the global ai market is valued at over  billion and is projected to increase in value by over x in the next  years😲  the global ai market is valued at over  billion and is projected to increase in value by over x in the next  years  global ai market valued billion projected increase value x next years  [global, ai, market, valued, billion, projected, increase, value, x, next, years]  global ai market valu billion project increas valu x next year
3                                  'Friends, Romans, countrymen, lend me your ears: I come to bury Caesar, not to praise him.'                                 'friends, romans, countrymen, lend me your ears: i come to bury caesar, not to praise him.'                                       friends romans countrymen lend me your ears i come to bury caesar not to praise him                                  friends romans countrymen lend me your ears i come to bury caesar not to praise him                                 friends romans countrymen lend me your ears i come to bury caesar not to praise him            friends romans countrymen lend ears come bury caesar praise              [friends, romans, countrymen, lend, ears, come, bury, caesar, praise]         friend roman countrymen lend ear come buri caesar prais
4                                                                    <html><body>Welcome to Text Pre-processing!</body></html>                                                                   <html><body>welcome to text pre-processing!</body></html>                                                                             htmlbodywelcome to text preprocessingbodyhtml                                                                        htmlbodywelcome to text preprocessingbodyhtml                                                                       htmlbodywelcome to text preprocessingbodyhtml                             htmlbodywelcome text preprocessingbodyhtml                                     [htmlbodywelcome, text, preprocessingbodyhtml]                       htmlbodywelcom text preprocessingbodyhtml
5                                                                              "🐍Python" is a great programming language!!! ??                                                                             "🐍python" is a great programming language!!! ??                                                                                  🐍python is a great programming language                                                                              🐍python is a great programming language                                                                              python is a great programming language                                       python great programming language                                             [python, great, programming, language]                                    python great program languag

In [31]:
#Lemmatization - reduces the inflected words properly ensuring the root word belongs to the language.

tdf["lemmatized"] = tdf["stopwords_removed"].apply(lambda x: " ".join([WordNetLemmatizer().lemmatize(word) for word in x.split()]))
tdf.iloc[:, 5:]

                                                       stopwords_removed                                                                          tokenized                                                         stemmed                                                            lemmatized
1                                       cant wait season stranger things                                             [cant, wait, season, stranger, things]                                 cant wait season stranger thing                                       cant wait season stranger thing
2  global ai market valued billion projected increase value x next years  [global, ai, market, valued, billion, projected, increase, value, x, next, years]  global ai market valu billion project increas valu x next year  global ai market valued billion projected increase value x next year
3            friends romans countrymen lend ears come bury caesar praise              [friends, romans, countrymen, lend, ears, come, bury, caesar, praise]         friend roman countrymen lend ear come buri caesar prais              friend roman countryman lend ear come bury caesar praise
4                             htmlbodywelcome text preprocessingbodyhtml                                     [htmlbodywelcome, text, preprocessingbodyhtml]                       htmlbodywelcom text preprocessingbodyhtml                            htmlbodywelcome text preprocessingbodyhtml
5                                      python great programming language                                             [python, great, programming, language]                                    python great program languag                                     python great programming language

In [32]:
# PART OF SPEECH (POS) Tagging - assigns grammatical categories to each word in a text. 

from nltk.tokenize import word_tokenize
from nltk import pos_tag
 
# Performing POS tagging
def pos_tagging(text):
    word_token = word_tokenize(text)
    return pos_tag(word_token)
    
print("Original Text:", tdf["sentences"].iloc[1])
print("\nPOS Tagging Result:",pos_tagging(tdf["sentences"].iloc[1]))

Original Text: The global AI market is valued at over $390 billion and is projected to increase in value by over 5x in the next 5 years😲.

POS Tagging Result: [('The', 'DT'), ('global', 'JJ'), ('AI', 'NNP'), ('market', 'NN'), ('is', 'VBZ'), ('valued', 'VBN'), ('at', 'IN'), ('over', 'IN'), ('$', '$'), ('390', 'CD'), ('billion', 'CD'), ('and', 'CC'), ('is', 'VBZ'), ('projected', 'VBN'), ('to', 'TO'), ('increase', 'VB'), ('in', 'IN'), ('value', 'NN'), ('by', 'IN'), ('over', 'IN'), ('5x', 'CD'), ('in', 'IN'), ('the', 'DT'), ('next', 'JJ'), ('5', 'CD'), ('years😲', 'NN'), ('.', '.')]

In [33]:
# CHUNKING - process of identifying parts of speech and short phrases in a sentence.

def chunking(text, grammar):
    word_tokens = word_tokenize(text)
    # Label words with part of speech
    word_pos = pos_tag(word_tokens)
    # create a chunk parser using grammar
    chunkParser = nltk.RegexpParser(grammar)
    # test it on the list of word tokens with tagged pos
    tree = chunkParser.parse(word_pos)
    
    for subtree in tree. subtrees():
        print(subtree)
    tree.draw()

sentence = tdf["sentences"].iloc[1]
grammar = "NP: {<DT> ?< JJ> *< NN>}"
chunking(sentence, grammar)

(S
  The/DT
  global/JJ
  AI/NNP
  (NP market/NN)
  is/VBZ
  valued/VBN
  at/IN
  over/IN
  $/$
  390/CD
  billion/CD
  and/CC
  is/VBZ
  projected/VBN
  to/TO
  increase/VB
  in/IN
  (NP value/NN)
  by/IN
  over/IN
  5x/CD
  in/IN
  the/DT
  next/JJ
  5/CD
  (NP years😲/NN)
  ./.)
(NP market/NN)
(NP value/NN)
(NP years😲/NN)

In [34]:
# NAMED ENTITY RECOGNITION - used to extract information from unstructured text.
#It classifies entities present in a text into categories like person, object, organization, etc


def named_entity_recognition(text):
    word_tokens = word_tokenize(text)
    word_pos = pos_tag(word_tokens)
    print(ne_chunk(word_pos))

named_entity_recognition(tdf["sentences"].iloc[1])

(S
  The/DT
  global/JJ
  AI/NNP
  market/NN
  is/VBZ
  valued/VBN
  at/IN
  over/IN
  $/$
  390/CD
  billion/CD
  and/CC
  is/VBZ
  projected/VBN
  to/TO
  increase/VB
  in/IN
  value/NN
  by/IN
  over/IN
  5x/CD
  in/IN
  the/DT
  next/JJ
  5/CD
  years😲/NN
  ./.)